// Generated by gencpp from file chassis_msgs/Ultrasonic.msg
// DO NOT EDIT!


#ifndef CHASSIS_MSGS_MESSAGE_ULTRASONIC_H
#define CHASSIS_MSGS_MESSAGE_ULTRASONIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace chassis_msgs
{
template <class ContainerAllocator>
struct Ultrasonic_
{
  typedef Ultrasonic_<ContainerAllocator> Type;

  Ultrasonic_()
    : header()
    , field_of_view(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , front_range(0.0)
    , back_range(0.0)
    , left_range(0.0)
    , right_range(0.0)  {
    }
  Ultrasonic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , field_of_view(0.0)
    , min_range(0.0)
    , max_range(0.0)
    , front_range(0.0)
    , back_range(0.0)
    , left_range(0.0)
    , right_range(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _field_of_view_type;
  _field_of_view_type field_of_view;

   typedef float _min_range_type;
  _min_range_type min_range;

   typedef float _max_range_type;
  _max_range_type max_range;

   typedef float _front_range_type;
  _front_range_type front_range;

   typedef float _back_range_type;
  _back_range_type back_range;

   typedef float _left_range_type;
  _left_range_type left_range;

   typedef float _right_range_type;
  _right_range_type right_range;





  typedef boost::shared_ptr< ::chassis_msgs::Ultrasonic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_msgs::Ultrasonic_<ContainerAllocator> const> ConstPtr;

}; // struct Ultrasonic_

typedef ::chassis_msgs::Ultrasonic_<std::allocator<void> > Ultrasonic;

typedef boost::shared_ptr< ::chassis_msgs::Ultrasonic > UltrasonicPtr;
typedef boost::shared_ptr< ::chassis_msgs::Ultrasonic const> UltrasonicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_msgs::Ultrasonic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_msgs::Ultrasonic_<ContainerAllocator1> & lhs, const ::chassis_msgs::Ultrasonic_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.field_of_view == rhs.field_of_view &&
    lhs.min_range == rhs.min_range &&
    lhs.max_range == rhs.max_range &&
    lhs.front_range == rhs.front_range &&
    lhs.back_range == rhs.back_range &&
    lhs.left_range == rhs.left_range &&
    lhs.right_range == rhs.right_range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_msgs::Ultrasonic_<ContainerAllocator1> & lhs, const ::chassis_msgs::Ultrasonic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_msgs::Ultrasonic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f639b4bb8af92c8a160357038429f7d";
  }

  static const char* value(const ::chassis_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f639b4bb8af92c8ULL;
  static const uint64_t static_value2 = 0xa160357038429f7dULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_msgs/Ultrasonic";
  }

  static const char* value(const ::chassis_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 field_of_view\n"
"float32 min_range\n"
"float32 max_range\n"
"float32 front_range\n"
"float32 back_range\n"
"float32 left_range\n"
"float32 right_range\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::chassis_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.field_of_view);
      stream.next(m.min_range);
      stream.next(m.max_range);
      stream.next(m.front_range);
      stream.next(m.back_range);
      stream.next(m.left_range);
      stream.next(m.right_range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ultrasonic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_msgs::Ultrasonic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_msgs::Ultrasonic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "field_of_view: ";
    Printer<float>::stream(s, indent + "  ", v.field_of_view);
    s << indent << "min_range: ";
    Printer<float>::stream(s, indent + "  ", v.min_range);
    s << indent << "max_range: ";
    Printer<float>::stream(s, indent + "  ", v.max_range);
    s << indent << "front_range: ";
    Printer<float>::stream(s, indent + "  ", v.front_range);
    s << indent << "back_range: ";
    Printer<float>::stream(s, indent + "  ", v.back_range);
    s << indent << "left_range: ";
    Printer<float>::stream(s, indent + "  ", v.left_range);
    s << indent << "right_range: ";
    Printer<float>::stream(s, indent + "  ", v.right_range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_MSGS_MESSAGE_ULTRASONIC_H
